version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongo-app
    environment:
      MONGO_INITDB_DATABASE: projectform
      MONGO_INITDB_ROOT_USERNAME: admin  
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_USERNAME: app
      MONGO_INITDB_PASSWORD: app

  app:
    environment:
      DATABASE_SERVICE_NAME: mongo-app
      MONGODB_USER: app
      MONGODB_PASSWORD: app
      MONGODB_DATABASE: projectform
      PORT: 8080
    container_name: front
    restart: always
    build: .
    ports:
      - "8080:8080"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-app
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password



