version: '3.1'

services:

  mongo:
    image: mongo
    container_name: database
    environment:
      MONGO_INITDB_DATABASE: prjform
      MONGO_INITDB_ROOT_USERNAME: admin  
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_USERNAME: app
      MONGO_INITDB_PASSWORD: app
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  app:
    environment:
      DATABASE_SERVICE_NAME: database
      MONGODB_USER: app
      MONGODB_PASSWORD: app
      MONGODB_DATABASE: prjform
      PORT: 8080
    container_name: front
    restart: always
    build: .
    ports:
      - "8080:8080"




